
[rule]
type = "query"
index = [".ds-logs-fortinet_fortigate.log-*"]
language = "kuery"
query = '''
fortinet.firewall.subtype:"virus"
'''
name = "FortiGate UTMVirus Detection"
description = "Detects FortiGate antivirus events."
severity = "medium"
risk_score = 47
tags = ["Tactic: Execution"]
references = ["https://docs.fortinet.com/document/fortigate/7.6.3/administration-guide/315155/testing-an-antivirus-profile"]
author = ["mitzep0x1"]

[[rule.threat]]
framework = "MITRE ATT&CK"
[rule.threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
